import { DeveloperModule } from '../models/DeveloperSettings';

export class DeveloperRepository {
  public getModules(): DeveloperModule[] {
    return [
      {
        id: 'medcore-library',
        name: 'Biblioteca do MedCore',
        description: 'Módulo funcional de gestão de acervo, metadados bibliográficos e suporte a multi-importação.',
        iconName: 'FolderOpen',
        category: 'sources',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['Multi-Upload', 'Filtros Avançados', 'Ações Bibliográficas', 'Status Importado'],
      },
      {
        id: 'knowledge-engine',
        name: 'Knowledge Engine',
        description: 'Motor de estruturação, indexação semântica e curadoria de conteúdo médico.',
        iconName: 'FolderGit2',
        category: 'knowledge',
        status: 'Em desenvolvimento',
        enabled: false,
        futureFormats: ['Vector DB', 'RAG Engine', 'Graph Index'],
      },
      {
        id: 'file-importer',
        name: 'Importador de Arquivos',
        description: 'Pipelines universais para ingestão e conversão de fontes bibliográficas.',
        iconName: 'FileSpreadsheet',
        category: 'sources',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['PDF', 'DOCX', 'PPTX', 'EPUB', 'OCR Vision'],
      },
      {
        id: 'books',
        name: 'Livros',
        description: 'Gestão de acervo de manuais, tratados médicos e compêndios essenciais com CRUD completo.',
        iconName: 'BookOpen',
        category: 'sources',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['CRUD Completo', 'Metadados Avançados', 'Busca por ISBN', 'Filtros por Categoria'],
      },
      {
        id: 'exam-bank',
        name: 'Banco de Provas',
        description: 'Repositório unificado de provas de Residência Médica, ENARE e Revalida com CRUD completo.',
        iconName: 'FileText',
        category: 'sources',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['CRUD Completo', 'Filtros por Instituição', 'Gabaritos', 'Busca Avançada'],
      },
      {
        id: 'bancas',
        name: 'Bancas',
        description: 'Perfis estatísticos e bancas examinadoras indexadas (USP, ENARE, AMP, etc.) com RAG.',
        iconName: 'Building2',
        category: 'sources',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['Vector Index', 'RAG Embeddings', 'Style Matrix'],
      },
      {
        id: 'professors',
        name: 'Professores',
        description: 'Modelagem de perfil didático, predileções de tópicos e vetores de professores indexados.',
        iconName: 'GraduationCap',
        category: 'sources',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['Vector Index', 'RAG Embeddings', 'Topic Frequency'],
      },
      {
        id: 'guidelines',
        name: 'Diretrizes',
        description: 'Consensos das Sociedades Brasileiras e Internacionais (AMB, SBC, FEBRASGO, MS, OMS) com CRUD completo.',
        iconName: 'BookMarked',
        category: 'knowledge',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['CRUD Completo', 'AMB/SBC/MS', 'Busca de Consensos', 'Resumos Executivos'],
      },
      {
        id: 'protocols',
        name: 'Protocolos',
        description: 'Algoritmos diagnósticos e condutas terapêuticas de emergência/UTI.',
        iconName: 'FileCode',
        category: 'knowledge',
        status: 'Em desenvolvimento',
        enabled: false,
        futureFormats: ['Decision Tree Parser', 'Step Verification'],
      },
      {
        id: 'ai-processing',
        name: 'Processamento IA',
        description: 'Orquestrador Gemini / LLM para geração automática de Flashcards e Questões.',
        iconName: 'Bot',
        category: 'ai',
        status: 'Em desenvolvimento',
        enabled: false,
        futureFormats: ['Gemini 3.6 Flash', 'Structured JSON Parser'],
      },
      {
        id: 'embeddings',
        name: 'Embeddings',
        description: 'Geração de vetores densos (gemini-embedding-001) para busca semântica instantânea.',
        iconName: 'Brain',
        category: 'ai',
        status: 'Em desenvolvimento',
        enabled: false,
        futureFormats: ['Vector Quantization', 'CosSim Search'],
      },
      {
        id: 'statistics',
        name: 'Estatísticas',
        description: 'Métricas de ingestão, acurácia de modelos e saúde do algoritmo SM-2.',
        iconName: 'BarChart2',
        category: 'system',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['Latency Analytics', 'Tokens Counter'],
      },
      {
        id: 'logs',
        name: 'Logs',
        description: 'Auditoria de segurança, falhas de sistema e rastreamento de tentativas de acesso.',
        iconName: 'ScrollText',
        category: 'system',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['Security Audit Trail', 'Console Logs'],
      },
      {
        id: 'backup',
        name: 'Backup',
        description: 'Snapshot do banco de dados local, exportação de flashcards e sincronização.',
        iconName: 'HardDrive',
        category: 'system',
        status: 'Em desenvolvimento',
        enabled: false,
        futureFormats: ['AES-256 Encrypted Zip', 'JSON Export'],
      },
      {
        id: 'settings',
        name: 'Configurações',
        description: 'Parâmetros de infraestrutura, alteração de PIN e chaves de APIs.',
        iconName: 'Settings',
        category: 'system',
        status: 'Ativo',
        enabled: true,
        futureFormats: ['PIN Manager', 'API Key Vault'],
      },
    ];
  }
}
